dependencies:
- name: jxboot-resources
  repository: http://chartmuseum.jenkins-x.io
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: http://chartmuseum.jenkins-x.io
- alias: jx-app-kuberhealthy
  condition: jx-app-kuberhealthy.enabled
  name: jx-app-kuberhealthy
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.2
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: http://chartmuseum.jenkins-x.io
- alias: bucketrepo
  condition: bucketrepo.enabled
  name: bucketrepo
  repository: http://chartmuseum.jenkins-x.io
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
- name: jx-app-datadog
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.7
- name: jx-tenant-service
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.453
- name: lighthouse-githubapp
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.577
- name: jxui-arcalos
  repository: https://charts.cloudbees.com/cjxd/cloudbees
  version: 0.0.1116
- name: jx-app-sso
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.29
